FROM node:18-slim

# Définir les variables d'environnement pour limiter la mémoire Node.js
ENV NODE_OPTIONS="--max-old-space-size=384"
ENV NODE_ENV="production"

# Créer le répertoire de l'application
WORKDIR /app

# Copier uniquement les fichiers nécessaires 
COPY package*.json ./

# Installer les dépendances en mode production (pas de devDependencies)
RUN npm ci --only=production --no-audit --no-fund

# Copier le code de l'application
COPY . .

# Définir le port à utiliser
ENV PORT=8080

# Exposer le port
EXPOSE 8080

# Démarrer l'application
CMD ["node", "--optimize_for_size", "--gc_interval=100", "server.js"]